From tomcat:apline
MAINTAINER Ashwani
WORKDIR $JENKINS_HOME/workspace/
COPY product-service_1-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/
RUN chmod -R 777
/usr/local/tomcat/webapps/product-service_1-1.0-SNAPSHOT.war
EXPOSE 8080
CMD /usr/local/tomcat/bin/catalina.sh run